containers/automation

- .mergify.yml
> Mergify: Remove existing WIP label

- .mergify.yml
> Mergify: Notice skipping of CI completely

- .cirrus.yml
- .github/workflows/cirrus-ci_retrospective.yml
- README.md
- bin/run_all_tests.sh
- cirrus-ci_retrospective/bin/cirrus-ci_retrospective.sh
- cirrus-ci_retrospective/bin/debug.sh
- cirrus-ci_retrospective/lib/cirrus-ci_retrospective.sh
- cirrus-ci_retrospective/lib/common.sh
- cirrus-ci_retrospective/test/run_all_tests.sh
- cirrus-ci_retrospective/test/test-cirrus-ci_retrospective.sh
- cirrus-ci_retrospective/test/testlib.sh
- common/lib/anchors.sh
- common/lib/console_output.sh
- common/lib/defaults.sh
- common/test/run_all_tests.sh
- common/test/test-anchors.sh
- common/test/test-console_output.sh
- common/test/test-defaults.sh
- common/test/testlib.sh
See the `README.md` changes for details.
> Implement common + cirrus-ci_retrospective + tests

- .github/workflows/cirrus-ci_retrospective.yml
- .github/workflows/release.yml
- .mergify.yml
> Minor release workflow cleanup

- README.md
- cirrus-ci_retrospective/README.md
> Improve documentation

- README.md
> Minor docs update

- .github/workflows/cirrus-ci_retrospective.yml
> Minor.  Empty body no work

- .github/workflows/cirrus-ci_retrospective.yml
> Fix YAML syntax typo

- cirrus-ci_retrospective/README.md
> Update retro. docs for manual tasks

- .github/workflows/cirrus-ci_retrospective.yml
> Add support for getting retro task status

- README.md
> Update README to use the latest tag

- .github/workflows/release.yml
- README.md
> Minor fix to release workflow

- .github/lib/cirrus-ci_retrospective.sh
It's possible that Cirrus-CI could re-execute a build/task after
previously having completed.  For example, due to a manual trigger or
re-run of a task.  This can result in the workflow triggered by the
first completion event, finding a build not in a final state.  If this
condition is detected, the workflow should not take any further action.
Presumably the in-flight (manual or re-run) will complete again at some
future time, causing the `on: check_suite: completed' workflow to execute
again.
> Avoid build status race

- CODE-OF-CONDUCT.md
- SECURITY.md
As the title says.
Signed-off-by: TomSweeneyRedHat <tsweeney@redhat.com>
> Add Code of Conduct and Security policies

- cirrus-ci_retrospective/Dockerfile
> Clarify purpose of defaulting to latest

- .cirrus.yml
- .github/workflows/action_helper_test.yml
- .github/workflows/cirrus-ci_retrospective.yml
- cirrus-ci_retrospective/test/testlib-cirrus-ci_retrospective.sh
- common/lib/console_output.sh
- common/lib/utils.sh
- common/test/testlib.sh
- ephemeral_gpg/.install.sh
- ephemeral_gpg/Containerfile
- ephemeral_gpg/Dockerfile
- ephemeral_gpg/README.md
- ephemeral_gpg/bin/debug.sh
- ephemeral_gpg/bin/ephemeral_gpg.sh
- ephemeral_gpg/lib/common.sh
- ephemeral_gpg/lib/ephemeral_gpg.sh
- ephemeral_gpg/lib/git_unattended_gpg.sh
- ephemeral_gpg/lib/git_unattended_gpg.sh.in
- ephemeral_gpg/test/run_all_tests.sh
- ephemeral_gpg/test/testbin-ephemeral_gpg-installer.sh
- ephemeral_gpg/test/testbin-ephemeral_gpg.sh
- ephemeral_gpg/test/testlib-ephemeral_gpg.sh
- ephemeral_gpg/test/testlib.sh
> Image for performing secure ephemeral gpg

- .github/workflows/cirrus-ci_retrospective.yml
> Correct improper workflow matrix use

- .github/workflows/cirrus-ci_retrospective.yml
> Remove unsupported yaml-anchor/alias

- .github/workflows/cirrus-ci_retrospective.yml
> Remove leftover matrix substitutions

- .github/workflows/cirrus-ci_retrospective.yml
> Fix incorrect artifact path and c_name typo

- .github/workflows/cirrus-ci_retrospective.yml
> Fix action-helper name

- common/lib/console_output.sh
- common/test/testlib-console_output.sh
> Add req_env_vars() function + tests

- common/lib/utils.sh
- common/test/testlib-utils.sh
> Fix exit behavior & tests

- cirrus-task-map/cirrus-task-map
- cirrus-task-map/test/cirrus-task-map.t
- cirrus-task-map/test/run_all_tests.sh
Generates a human-readable graph showing dependencies between
Cirrus tasks.
Requires: graphviz. Will use ImageMagick, if available, to
add a signature at bottom left (timestamp, tool version)
> New tool: cirrus-task-map

- common/lib/console_output.sh
- common/lib/defaults.sh
- common/test/testlib-console_output.sh
- github/test/testlib-github_common.sh
> Add show_env_vars function and tests

- common/lib/console_output.sh
- common/test/testlib-console_output.sh
> Simplify indent function and tests

- cirrus-task-map/cirrus-task-map
Stole code from: https://www.perlmonks.org/?node_id=813443
Further context: https://www.perlmonks.org/?node_id=1124136
> UGLY: deal with YAML anchors.

- common/lib/console_output.sh
> Avoid double-escaping env. var values

- .github/workflows/release.yml
- .github/workflows/ubuntu_unit_tests.yml
- ephemeral_gpg/lib/ephemeral_gpg.sh
> fix ephemeral_gpg unit tests

- .github/workflows/release.yml
- .github/workflows/ubuntu_unit_tests.yml
> Deduplicate Ubuntu unit tests

- common/lib/console_output.sh
- common/test/testlib-console_output.sh
> Add common showrun() function and unit-tests

- cirrus-task-map/cirrus-task-map
- task-map: show skippable tasks
- add only-ifs from automation_images repo
- More skip special-cases
> map show skip

- cirrus-ci_env/.install.sh
- cirrus-ci_env/test/run_all_tests.sh
- cirrus-ci_env/test/testbin-cirrus-ci_env-installer.sh
> Add cirrus-ci_env installer script and test

- cirrus-ci_env/cirrus-ci_env.py
- cirrus-ci_env/test/run_all_tests.sh
- cirrus-ci_env/test/test_cirrus-ci_env.py
- cirrus-ci_env/test/testbin-cirrus-ci_env.sh
* Use logging module for debugging and errors
* Show helpful message for legacy-format matrix
> Cirrus-ci_env debugging and matrix-error context message

- cirrus-ci_env/cirrus-ci_env.py
- cirrus-ci_env/test/actual_cirrus.yml
- cirrus-ci_env/test/expected_cirrus.yml
- cirrus-ci_env/test/expected_ti.yml
> Fix bug caused by prior commit

- README.md
- bin/install_automation.sh
- cirrus-ci_retrospective/README.md
> Handle update from master -> main

- bin/install_automation.sh
- common/test/testbin-install_automation.sh
> Update prior installer versions def. branch

- .github/workflows/cirrus-ci_retrospective.yml
> Minor/cosmetic master->main workflow update

- README.md
- build-push/README.md
> [CI:DOCS] Update readme's

- cirrus-ci_env/cirrus-ci_env.py
- cirrus-ci_env/test/actual_cirrus.yml
- cirrus-ci_env/test/actual_task_names.txt
- cirrus-ci_env/test/expected_cirrus.yml
- cirrus-ci_env/test/expected_ti.yml
Also update test data to confirm EC2 instance task parsing.
> Add support for ec2_instance task type

- .github/renovate.json
- .github/renovate.readme
Remove some experimental settings, retain only those relevant to this repository.
> Simplify + Further document config.

- .github/renovate.json
- .github/renovate.readme
Remove grouping, open separate PRs for each update.
> [skip ci] Renovate configuration tweaks

- .github/workflows/release.yml
- github/lib/github_common.sh
- github/test/testlib-github_common.sh
ref:
https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter
> Update github lib to new output standard

- renovate/defaults.json5
> Remove upstream issue 16715 workaround

- renovate/defaults.json5
Also, consolidate rules under the regex manager block.
> Assign CI VM Image update PRs

- renovate/defaults.json5
checked with:
podman run -it \
-v ./renovate/defaults.json5:/usr/src/app/renovate.json5:z \ docker.io/renovate/renovate:latest \
renovate-config-validator
Due the nested packageRules section in golang the auto migration is not working correctly and caused an error for us. This caused renovate to propse PRs without the proper settings.
Fix the config by (hopefully) migrating correctly to the new format. The nested packageRule is now on the same level which should fix the breakage. The config validator is happy now but I have no way of actually testing if this still works correctly, I guess we will find out.
output of the validate tool on the old (now) broken conf:
```
$  podman run -it \
-v ./renovate/defaults.json5:/usr/src/app/renovate.json5:z \
docker.io/renovate/renovate:latest \ …
```
> fix broken renovate config

- .cirrus.yml
- mac_pw_pool/.gitignore
- mac_pw_pool/Cron.sh
- mac_pw_pool/Utilization.gnuplot
- mac_pw_pool/html/index.html
This makes it easy to serve so more than one person may observe easily.
> Output web page with utilization graph

- mac_pw_pool/Cron.sh
- mac_pw_pool/nightly_maintenance.sh
Also relocate usage-graph web container and logfile maintenance to a dedicated script + crontab entry.
> Minor: Update example crontab

- mac_pw_pool/setup.sh
Ref: https://github.com/containers/skopeo/pull/2344
> Mac PW Pool: Install packages needed for skopeo CI

- mac_pw_pool/SetupInstances.sh
Previously when using the `--force` option to `SetupInstances.sh` each
instance created would have its lifetime extended by
`$CREATE_STAGGER_HOURS`. For any instance beyond the first, that will
immediately put it beyond the `$PW_MAX_HOURS` hard-limit.  Eventually
this will result in multiple instances going offline at the same time,
which is undesirable.
Fix this by staggering instance lifetimes with decreasing values instead.
Include extra checks to make sure the value remains positive and sane.
> Fix extending PW beyond PW_MAX_HOURS

- mac_pw_pool/README.md
Several sections and individual items were duplicated or did not belong in this file.  They've been moved to the private google-doc linked in the "Prerequisites" section and included in the monitoring website `index.html`.
> De-duplicate PW pool readme

- .github/workflows/cirrus-ci_retrospective.yml
Missed one place where I had to replace the arguments.
> github: fix wrong action call
