containers/automation

.mergify.yml
There are a few specific conditions under which mergify cannot
automatically merge a PR.  Some are internal, others are enforced
by github.  This can be extremely confusing to debug, so use
mergify to label these PRs appropriatly and block auto-merging.
=> Mergify: Detect required manual merge

.github/workflows/cirrus-ci_retrospective.yml
The github-script action will fail when instructed to remove a label
which is not already present on an issue.  Place this step at the end
of the workflow, and make it conditional on cancellation or failure only.
=> Fix removal of label

bin/install_automation.sh, common/test/testbin-install_automation.sh
It should be possible to execute the install script stand-alone, from
outside of the repository.  However, this could fail if an optional
component cannot be located.  Update the installer code to treat
this component as optional, ignoring errors if any.
=> Fix installer not finding ooe.sh

.github/workflows/cirrus-ci_retrospective.yml, cirrus-ci_retrospective/README.md, cirrus-ci_retrospective/bin/cirrus-ci_retrospective.sh
Both of these values are handy to have, and in some cases required.  For
example, the task ID is needed for triggering a re-run via the Cirrus-CI
GraphQL API.
=> Add retrieval of task and build id values

bin/install_automation.sh
Ubuntu defaults to `dash` as the system-wide shell which
means bash-isms in /etc/environment will fail.  Fix this
by reverting to simple-interpretation when referencing `$PATH`
to avoid screwing it up system-wide.
=> Use dash compatible environment

bin/install_automation.sh, common/bin/xrtry.sh
For whatever reason, the embedded PATH variable reference does not get
expanded in /etc/environment.  Fix this by simply dumping whatever
value resolves at install-time.
Also include small typo-fix for xrtry.sh script
=> Fix Ubuntu environment again

common/lib/console_output.sh
For some input line values, escape-characters were being eaten.  Fix this by
not interpreting the input line in any way, simply prefix each line with
spaces.
=> Simplify indent function

cirrus-ci_retrospective/lib/ccir_common.sh, common/lib/common_lib.sh, github/lib/github_common.sh
One internal, and several external users of this library don't bother
sourcing individual `common/lib/*.sh` files.  Instead they iterate
over all of them by name, which is messy and inconvenient.  Add a
short-cut script which callers can source to load all common libraries.
=> Add shortcut for loading all common libraries

.cirrus.yml, ci/Dockerfile, cirrus-task-map/test/run_all_tests.sh
Specifically, running tests for `cirrus-task-map` requires some perl
modules which are not needed in the `cirrus-ci_retrospective`
container (formerly used for CI).  Having a dedicated container
means the package-set can be specialized for testing needs.
=> Use dedicated CI container

bin/run_all_tests.sh, ci/Dockerfile
As of the release of Fedora 33, the FindBin perl module is now provided
by a dedicated package.  Previously it was part of the perl-interpreter
package.
For some unit-tests, it may become necessary in the future to utilize
Cirrus-CI env. vars. if they are set.  Ensure the top-level runner
exports them when they are available.
=> Update CI Container packages + export env. vars.

common/lib/console_output.sh, common/test/console_output_test_helper.sh, common/test/testlib-console_output.sh, github/test/testlib-github_common.sh
Previously due to practical reasons, the unit-tests did a very poor
jobs checking the code-context information shown by functions like
`die()`.  Prior to this commit, the stack-level used was too great,
resulting in unhelpful output such as:
`ERROR: blah blah blah (<stdin>:0 in ())`
Fix the stack-level and context output.  Add a helper-script
and new unit-test to confirm it does not break again in the future.
=> Fix code-context references

cirrus-ci_asr/README.md, cirrus-ci_asr/cirrus-ci_asr.py, cirrus-ci_asr/requirements.txt, cirrus-ci_asr/test/run_all_tests.sh
This is an incredibly basic implementation, and a simple "does it run" test.  It is needed in the short-term for use in [*other scripts*], to help process and debug incidents of "CI Agent Stopped Responding" tasks.  Adding it into this repo. as a reference for future similar/related scripts.
Ref: https://github.com/containers/podman/issues/8068 Intended use by [*other scipts*]:
* Allow debugging of leftover VMs for which a task failed due to "CI Agent Stopped Responding" (see https://github.com/containers/podman/issues/8068#issuecomment-716573893)
* Allow cleanup of all leftover VMs for which a task failed due to any reason.
=> Implement helper for processing specific failed CI jobs

ci/Dockerfile, cirrus-ci_env/cirrus-ci_env.py, cirrus-ci_env/test/actual_cirrus.yml, cirrus-ci_env/test/actual_task_names.txt, cirrus-ci_env/test/expected_cirrus.yml, cirrus-ci_env/test/expected_ti.yml, cirrus-ci_env/test/run_all_tests.sh, cirrus-ci_env/test/test_cirrus-ci_env.py, cirrus-ci_env/test/testbin-cirrus-ci_env.sh, cirrus-ci_env/test/testlib.sh
The current `get_ci_vm.sh` script is duplicated in each repo with
slight changes, and is therefore difficult to maintain.  This
commit adds a helper script to solve several problems blocking
development of a unified `get_ci_vm.sh`.  Given a (Cirrus-CI
validated) `.cirrus.yml`:
* What is the complete set of task names configured (including matrix
tasks)
* What environment variables should be set for any given task.
* What kind of runtime instance should be used (i.e. VM or Container)
for a task.
* What is the VM or container image name to use used for a task
Also, add unit, integration, and system tests for this tool along with
lint and style checking.
=> Implement cirrus-ci config task env. var. renderer

cirrus-ci_env/cirrus-ci_env.py, cirrus-ci_env/test/test_cirrus-ci_env.py
=> Fix traceback when task or matrix has no env.

cirrus-ci_env/cirrus-ci_env.py
This was replaced in Cirrus with 'macos_instance', update code
accordingly to support both.
=> Fix deprecated "osx_instance" type

bin/install_automation.sh, common/test/testbin-install_automation.sh
Under some execution contexts (i.e. `sudo`), under some flavors of bash,
these special device files may not be accessable.  Refrain from using
them during the install process.
=> Fix /dev/stderr: permission denied

.cirrus.yml
The branch was renamed long ago, but this change was missed due to the
only check using it was negative.  Fix this so it's easier to understand
the task which should only run in PRs.
=> Fix master branch reference

.cirrus.yml, README.md, build-push/.install.sh, build-push/README.md, build-push/bin/build-push.sh, build-push/test/fake_buildah.sh, build-push/test/qemusetup.sh, build-push/test/run_all_tests.sh, build-push/test/test_context/Containerfile, build-push/test/testbin-build-push.sh, build-push/test/testbuilds.sh, build-push/test/testlib.sh, common/lib/common_lib.sh, common/lib/platform.sh, common/test/testlib-platform.sh
This will partially address https://github.com/containers/buildah/issues/3268 but the initial intent is to include this script in podman/buildah/skopeo automation.  So there may be some initial end-user unfriendliness.
=> [WIP] Multi-arch build-push helper script

.cirrus.yml, build-push/bin/build-push.sh, build-push/test/fake_buildah.sh, build-push/test/testbin-build-push.sh
It's necessary for downstream usage that both a --modcmd and --prepcmd
script have access to the parsed value from --arches.  Prior to this
commit, the value was stored in an array.  Unf., many versions of bash
do not yet support export of array variables.  This commit converts it
into a simple space-separated string and adds a test to confirm.
While fixing this, it was discovered that the handling of \$BUILD_ARGS
was also wrong.  Both quoting and any use of embedded special characters
(like whitespace) would not be preserved.  It was also marked as a
variable exported to to --prep/--modcmd, which is not possible.  Fix
this by removing it from the export list, and tweak the processing and
use of \$BUILD_ARGS in general.  Add a test to confirm proper handling
of both quotes and special …
=> Fix exports

cirrus-task-map/cirrus-task-map
CI:BUILD and the new 'release|bump' check
=> task-map: handle two new podman conditions

build-push/bin/build-push.sh, build-push/test/fake_buildah.sh, build-push/test/testbin-build-push.sh
When executing build-push.sh with the `--arches=*` option, the script
automatically includes the local architecture by default.  This may
be counter-intuitive and is contrary to the documentation for this
option.  Worse, if the local architecture is specified as an
`--arches` argument, buildah will build TWO images for it. Fix this
by excluding the default local-arch value when processing the
`--arches` command-line option.
=> Fix automatic inclusion of local arch

cirrus-ci_retrospective/Dockerfile
Fixes https://github.com/containers/automation/runs/5425690658?check_suite_focus=true#step:4:12
=> Fix cirrus-ci_retrospective image missing python3

bin/install_automation.sh, github/.install.sh
In nearly all use-cases, users of the automation libraries/tools need to
both load and export variables in this file.  Otherwise loading
additional libraries (which depend on the variables) will fail.  Make
this easier on downstream users by exporting important variables in-line
in this file.
=> Make /etc/automation_environment easier to consume

cirrus-ci_retrospective/lib/cirrus-ci_retrospective.sh
Should a GraphQL query not satisfy the schema, the server will
frequently return a JSON formatted error message.  The
cirrus-ci_retrospective library checks for this by using a naive
`grep` command.  However, this could mistakenly trigger on the `error`
term naturally appearing in a non-error/valid response.  Remove this
check.  Instead, enhance the existing `filter_json()` checks by
causing jq to exit non-zero for invalid JSON replies.  Assume callers
of cirrus-ci_retrospective will be sensitive to an error reply from
the server, and handle it accordingly.
=> Fix overly inclusive error check

README.md
The github annotated URL was referenced instead of the "raw" download
URL.  Fix it.
=> Fix installer download URL

cirrus-ci_env/cirrus-ci_env.py, cirrus-ci_env/test/actual_cirrus.yml, cirrus-ci_env/test/actual_task_names.txt, cirrus-ci_env/test/expected_cirrus.yml, cirrus-ci_env/test/expected_ti.yml, cirrus-ci_env/test/test_cirrus-ci_env.py
Also fix attempts to expand `$PATH`, this variable is handled specially by Cirrus-CI so it can just be ignored.
=> Add parser support for windows container tasks

.github/workflows/action_helper_test.yml, .github/workflows/ubuntu_unit_tests.yml
There are several jobs called `unit-tests`.  Rename them with a prefix to clarify exactly what they're testing.  Also, add a run of the (renamed) `automation_unit-tests` to happen at branch-push time.
=> Rename GHA jobs to remove ambiguity

.github/renovate.json5, default.json, renovate/defaults.json5
JSON5 is far more readable, but cannot be used for the default. Workaround this by referencing a JSON5 preset from the default JSON preset.
=> Redirect default JSON config to path'd JSON5 config

renovate/defaults.json5
This was recommended by the upstream Renovate community: "Nesting packageRules under language objects can have unintended consequences".
=> Separate out packageRules from golang config object

renovate/defaults.json5
Github-action updates cannot consistently be tested in a PR. This is caused by an unfixable architecture-flaw: Execution context always depends on trigger, and we (obvious) can't know that ahead of time for all workflows.  Abandon all hope and mark github-action dep. update PRs '[skip-ci]'
=> Teach renovate to [skip-ci] on github-action deps

renovate/defaults.json5
This compliments the date/time based versioning implemented in https://github.com/containers/automation_images/pull/247
Once merged, these changes will result in renovate opening PRs for tagged CI VM image commits in containers/automation_images. Renovate will ignore any existing configurations using the old `$CIRRUS_BUILD_ID` based *IMAGE_SUFFIX* values.
=> Manage CI VM image updates with renovate

renovate/defaults.json5
Two versions released on accident have been retracted but renovate version retraction isn't working right.  Centralize a package rule to ignore the "bad" versions for all repos.
=> Centralize c/common version retraction

renovate/defaults.json5
Ref: https://github.com/containers/skopeo/issues/1926
According to the PR descriptions linked in the above issue:
Schedule: Branch creation - At any time
Attempt to impose the intended monthly schedule by disambiguating the digest-update package-rule under the golang-manager configuration.  I have no idea if this will actually resolve the underlying problem, but it does lead to a more organized configuration.
=> [CI:DOCS] Attempt to fix ineffective digest schedule

bench_stuff/.install.sh, bench_stuff/README.md, bench_stuff/bench_stuff.py, bench_stuff/test/test_bench_stuff.py
Move metadata values from a nested to the top-level document structure.
This makes both indexing and querying the data-point simpler.  Also add
an expiry meta-data field recording a date/time 30-days in the future.
=> Update bench_stuff schema

bench_stuff/bench_stuff.py, bench_stuff/test/test_bench_stuff.py
* Fix a verbose message referencing an prior-implementation collection name (type).
* Rename the timestamp field to `occasion` since IMHO that's a more meaningful representation of it's identity.
* Increase the expiration time for new entries to 180 days since IMHO that better reflects their useful lifetime.
* Include the HEAD commit-ID with benchmark meta-data
* Bump the schema version to 3 due to field name changes.
=> Bench_stuff: Several minor fixups 

renovate/defaults.json5
The original discussion about this has been closed.  At the time, I believe I remember seeing a bugfix go through in the renovate change-logs.  In any case, it seems [rollback PRs are not working correctly](https://github.com/containers/podman/issues/18139#issuecomment-1517532310). Remove the workaround and enable rollbackPRs by default for golang.
=> Remove golang rollback PRs workaround

renovate/defaults.json5
Otherwise this would be limited to the global default: once per week.
=> Allow Renovate CI VM Updates at any time

renovate/defaults.json5
There's no reason to capture major/minor/patch components (and they may be unhelpful/confusing/broken in some cases).  Simplify the setup to use "autoReplaceStringTemplate" to guide the replacement, and  "loose" versioning tell renovate to do a simple value sort on the github-tags.
=> Simplify renovate CI VM image updates

cirrus-ci_artifacts/requirements.txt, renovate/defaults.json5
For CI VM Image update PRs, add me as a reviewer instead of assignee. This is more appropriate to the action needed for these PRs.
Also fix urllib3 problem, ref: https://stackoverflow.com/questions/76175487/sudden-importerror-cannot-import-name-appengine-from-requests-packages-urlli
=> Switch assignees to reviewers + fix broken urllib3 dep.

cirrus-task-map/cirrus-task-map
- cirrus-task-map: explicit YAMLs always override anchors
- task-map: hardcode in a few more only-ifs
=> task-map: handle rawhide, treadmill, "bench stuff"

cirrus-ci_env/cirrus-ci_env.py
Fix unit test failure: `./cirrus-ci_env.py:123:26: E275 missing whitespace after keyword`
=> Minor: Fix flake8 finding

common/lib/platform.sh, common/test/testlib-platform.sh
This is esp. used during CI VM image builds where only a user account is available for some stages.  It's important to block `sudo apt-get` calls from asking for user input during update/install.
=> Support $SUDO setup for debian environments

common/lib/defaults.sh, common/lib/platform.sh, common/test/testlib-platform.sh, common/test/testlib.sh
This function is otherwise duplicated in both buildah and podman CI, along with it's associated env. vars.  Provide it here to help limit duplication and cover it with testing.
=> Add passthrough_envars() function and test

renovate/defaults.json5
Not sure why but the config change in commit 8f61a71 caused us to now
get rollback PRs for digest updates which is wrong and very noisy.
Let's keep them disabled for now and let Chris figure it out when he is
back.
@vrothberg @edsantiago PTAL again i.e. https://github.com/containers/podman/pull/19206
This should not be created.
=> renovate: disable rollbackPrs

renovate/defaults.json5
Ref: https://github.com/containers/netavark/issues/772
=> Renovate: Slow down 'serde' and 'clap' updates

build-push/bin/build-push.sh, build-push/test/fake_buildah.sh
Around the time of this commit, [the automated multiarch manifest-list builds for both skopeo and podman have been failing](https://cirrus-ci.com/task/5905066138271744?logs=main#L985) somewhere in the `build-push.sh` script.  The actual build appears to work fine, the `tag-version.sh` mod-command runs fine, but the tag-search in `get_manifest_tags()` (called by `push_images()`) fails with the error:
`jq: error (at <stdin>:29): Cannot iterate over null (null)`
Unfortunately the problem does not reproduce for me locally, nor can it be reproduced using a dry-run build (`--nopush` bypasses the tag search.) Improve debugging of this situation by moving the `if ((PUSH))` check and adding an exception clause to display the would-be pushed images (and tags).
Also:
* Simplify the …
=> Improve build-push error handling

renovate/defaults.json5
In podman CI golangci-lint is only run in the validate step so there is no point in running the full test suite for such updates. The validate task is included with CI:DOCS so that should be good enough even if it is technically not a doc change.
=> renovate: add CI-colon-DOCS prefix for golangci-lint updates

bin/install_automation.sh
Otherwise the timestamp is localized, which may be harder for humans
to relate/translate WRT other time-based items.  For example, Cirrus-CI
and GHA cron specifications.  Also add mention of the just-installed
version to the env. file, also to help with any needed auditing.
=> Minor: Breadcrumb version and UTC timestamp

mac_pw_pool/.gitignore, mac_pw_pool/InstanceSSH.sh, mac_pw_pool/LaunchInstances.sh, mac_pw_pool/README.md, mac_pw_pool/SetupInstances.sh, mac_pw_pool/ci_env.sh, mac_pw_pool/pw_lib.sh, mac_pw_pool/service_pool.sh, mac_pw_pool/setup.sh
Implement a set of scripts to help with management of a Cirrus-CI persistent worker pool of M1 Mac instances on AWS EC2.
* Implement script to help monitor a set of M1 Mac dedicated hosts, creating new instances as slots become available.
* Implement a script to help monitor M1 Mac instances, deploying and executing a setup script on newly created instances.
* Implement a ssh-helper script for humans, to quickly access instances based on their EC2 instance ID.
* Implement a setup script intended to run on M1 Macs, to help configure and join them to a pre-existing worker pool.
* Implement a helper script intended to run on M1 Macs, to support developers with a CI-like environment.
* At this time, all scripts are intended for manual/human-supervised use.  Future commits may improve this …
=> Cirrus-CI persistent worker pool management

mac_pw_pool/LaunchInstances.sh, mac_pw_pool/README.md, mac_pw_pool/SetupInstances.sh, mac_pw_pool/service_pool.sh, mac_pw_pool/setup.sh
When a pool is empty of instances, the launch-stagger mechanism can introduce a substantial delay to achieving a full-pool of active workers.  This will negatively impact service availability and worker utilization - likely resulting in CI tasks queuing.
Add a simple workaround for this condition with the addition of a `--force` option.  When used, it will force instance creation on all available dedicated hosts.  Similarly it will also force instance setup, though with an extended shutdown delay timer.
Update documentation regarding this operational mode and it's purpose.
=> Workaround lengthy startup of many instances

mac_pw_pool/SetupInstances.sh, mac_pw_pool/service_pool.sh, mac_pw_pool/setup.sh
It's helpful for operators to be aware of the expiration-time for workers.  Ensure this, along with any other `service_pool.sh` messages are logged.  Extract and display the logged expiration notice, or a warning if missing.  The constant log-grep is secondarily useful as indication of worker log-file manipulation.
=> Better logging of worker expiration

mac_pw_pool/LaunchInstances.sh, mac_pw_pool/pw_lib.sh
With an active and in-use dedicated host pool, it's very hard to test changes to management scripts.  Add support for filtering the list of DH to operate on, based on a defined tag name and value.  This way, inactive DH can be manually re-tagged (temporarily) to allow testing script changes against them.
=> Allow dividing DH pool based on tag name/value

mac_pw_pool/service_pool.sh
The darwin version of sleep doesn't support any suffix, and breaks if you use one.  Fix the script and adjust the timings so the loop runs quicker.
This has been tested on the currently in-use pool.
=> Fix sleep typo + reduce times

mac_pw_pool/service_pool.sh
Fix typo in calculating sleep seconds.  Remove mode `e` from script, so any failing command (i.e. a pgrep) doesn't cause the script to exit. Also redirect null input into shutdown command, since it can behaves oddly otherwise.
=> Fix two pool service script failure-modes

mac_pw_pool/.gitignore, mac_pw_pool/Cron.sh, mac_pw_pool/InstanceSSH.sh, mac_pw_pool/LaunchInstances.sh, mac_pw_pool/README.md, mac_pw_pool/SetupInstances.sh, mac_pw_pool/Utilization.gnuplot, mac_pw_pool/pw_lib.sh, mac_pw_pool/service_pool.sh, mac_pw_pool/setup.sh, mac_pw_pool/shutdown.sh
The initial implementation was rushed into production with a minimum of
required features, and necessary amount of slop and bugs.  Attend to
a litany of needed improvements and enhancements:
* Add tracking of both started and completed tasks.
* Update utilization CSV entry addition to include tasks-ended
(`taskS`).
* Update instance-ssh helper to support specifying by name or ID
* Fix multiple instance-ssh helper executions clashing over VNC port
forwards.
* Update many comments
* Fix handling of case where no dedicated hosts or instances are found.
* Relocate `CREATE_STAGGER_HOURS` to `pw_lib.sh` and lower value to 2.
This value should not include a margin representing boot/setup time.
Also a lower value will allow for faster automated pool recovery
should the entire thing collapse for …
=> Improve/overhaul pool management/monitoring scripts

mac_pw_pool/setup.sh
Podman machine testing is very much storage-bound in terms of performance.  The stock AWS setup uses networked storage for the system, and a small local disk for `/tmp`.  However there is plenty of empty space available on the local disk, and it's *MUCH* faster than network storage.  Use this disk as the worker-user's home directory (where tests run from).
=> Create, mount, and use local storage

common/lib/platform.sh, common/test/testlib-platform.sh
Because otherwise, as the saying goes:
"There's nothing more permanent than temporary"
Inspiration: https://github.com/containers/automation_images/pull/312/files#r1396326242
=> Add common timebomb function to mark workarounds

common/test/testlib-platform.sh
The "timebomb() function ignores TZ envar and forces UTC" test started failing (triggering the bomb unintentionally).  Fixed by forcing the in-line date-calculation to be based on UTC (which the test was assuming previously).  Also updated the subsequent test similarly, for consistency.
=> Fix timebomb test using wrong basis

mac_pw_pool/Cron.sh, mac_pw_pool/nightly_maintenance.sh
Previously, the automation repo was updated by a cron job w/o regard to possibly, currently executing scripts.  This is bad.  Fix the situation by only updating the repo. while holding a `Cron.sh` lock, taking care to restart the graph-presenting webserver container as required.
=> Synchronize maintenance script changes

README.md, bin/run_all_tests.sh, build-push/bin/build-push.sh, build-push/test/fake_buildah.sh, build-push/test/testbuilds.sh, cirrus-ci_artifacts/cirrus-ci_artifacts, cirrus-ci_artifacts/test/test_cirrus-ci_artifacts.py, cirrus-ci_retrospective/lib/cirrus-ci_retrospective.sh, common/bin/ooe.sh, common/lib/anchors.sh, common/lib/console_output.sh, common/lib/platform.sh, common/test/run_all_tests.sh
Redirecting to `/dev/stderr` or `/dev/stdout` can have a normally unintended side-effect when the caller wishes to send either of those elsewhere (like an actual file).  Namely, it will truncate the file before writing.  This is almost never the expected behavior.  Update all redirects to magic devices to append instead.
N/B: These scripts are used far and wide.  On the off-chance some downstream caller has previously depended on this side-effect, I'm marking this commit as 'breaking' accordingly.
=> [5.0.0] Fix truncating stdio magic devices

mac_pw_pool/setup.sh
There's no point of this operation on a CI machine, and it creates non-deletable files for every user on the system.  Stop it for all volumes, ignoring any failures.
=> Mac PW Pool: Stop indexing local disks

cirrus-task-map/cirrus-task-map
For handling recent (Feb 2024) changes to .cirrus.yml
=> cirrus-task-map: more shortcuts

mac_pw_pool/nightly_maintenance.sh
Previously an unnecessarily complex mechanism was used to automatically update the code on the Mac PW Pool maintenance VM.  Simplify this to a short fixed time interval to improve reliability.  Also fix a minor bug where the web container restarted attached rather than detached.
=> Simplify pool maintenance script updates

renovate/defaults.json5
Lots of module updates are arriving which require this version, unblock all repos that depend on it.
=> Bump golang to version 1.21

build-push/bin/build-push.sh, build-push/test/testbuilds.sh
Prior to https://github.com/containers/image_build/pull/23 the
automation using `build-push.sh` always pushed its images.  This
obscured a bug that occurs when `fqin_names` is an empty string in
`get_manifest_tags()`.  In this case, the `grep` command will exit
non-zero, causing `push_images()` to:
```
die "Error retrieving set of manifest-list tags to push for '$FQIN'"
```
Fix this by adding an empty-string check and removing the unnecessary
`grep`.  Also, `push_images()` change `die "No FQIN(s) to be pushed."`
into a warning, since the condition should not be considered fatal.
=> Fix build-push failing on empty push list 

renovate/defaults.json5
Fixes: #193
Despite restrictions on `go` directive updates by Renovate, it was still proposing updates to the `toolchain` directive.  In order to maintain consistency across all projects, this value needs to be managed manually.  Detect when Renovate is trying to update it and shut it down.
Ref: Upstream https://github.com/renovatebot/renovate PR 28476
=> Never update golang toolchain

mac_pw_pool/setup.sh
Podman machine testing needs rosetta to confirm running x86_64 binaries.
Ref: https://github.com/containers/podman/pull/22773
=> Mac PW Pool: Install rosetta

mac_pw_pool/README.md, mac_pw_pool/setup.sh
For whatever reason, non-admin users are permitted to install and update software on Macs by default.  This is highly undesirable in a CI environment, and especially so in one where the underlying resources are shared across testing contexts.  Block this by altering system settings to require admin access.
Further through experimentation, it was found that rosetta (allows arm64 macs to run x86_64 code) ignores the admin-required settings.  To give pause to any users trying to run `softwareupdate`, move it out of general reach.  This isn't a perfect solution, but should at least discourage all simple usage.
=> Mac PW Pool: Restrict software installation/updates

mac_pw_pool/pw_lib.sh
Previously instances would shutdown and auto-terminate if the controlling VM's `SetupInstances.sh` examined the remote worker log and found >= `PW_MAX_TASKS` logged.  However after examining the production `Cron.log`, it was found that nowhere near this number of tasks is actually running during `PW_MAX_HOURS`.  Cut the value in half to lower the risk of one/more tasks corrupting processes or the filesystem for other tasks.
Note: Eyeball average tasks before timed auto-shutdown was about 7
=> PW Pool: Reduce task-to-task corruption risk

renovate/defaults.json5
Discovered by log analysis, Renovate will initially setup a vulnerable golang indirect dep for immediate PR creation.  However, later on in its run, PR creation will be disabled by the global indirect-golang default setting (disabled).  Extensive review of `packageRules` configuration shows no way to filter based on vulnerability status. This would be the only conceivable way to override the default.
Fix this by replacing the misleading/useless config. section with a comment block indicating that indirect golang vulnerabilities must be handled by hand.
=> Unconfigure golang indirect vulnerability support

cirrus-task-map/cirrus-task-map
- ImageMagick v7 deprecates "convert" command
- cirrus-task-map: add skips/only-ifs for automation_images
=> cirrus-task-map: tweaks for automation_images CI

cirrus-task-map/cirrus-task-map
They are now under only_if, not skip. And there's really no need
for individual names, just say "SKIP if not needed"
Also, add handling for 'skip CI=CI', currently used in minikube
=> Simplify the new podman CI skips

mac_pw_pool/AllocateTestDH.sh, mac_pw_pool/Cron.sh, mac_pw_pool/LaunchInstances.sh, mac_pw_pool/README.md, mac_pw_pool/Utilization.gnuplot, mac_pw_pool/pw_lib.sh
Previously a lot of intricate and painful steps were requred to setup a
Mac dedicated-host for testing.  Make this process easier with a script
that does most of the work.  Update documentation accordingly.
=> Mac PW Pool: Add testing helper script 

.cirrus.yml
Newer renovate container images place the binary elsewhere, resulting in
this check encountering a file-not-found error.
=> Fix running renovate-config-validator

mac_pw_pool/setup.sh
In order to test accessibility of the host GPU inside a podman machine
container, it's necessary to install support for krun.  However, since
the list of brew recipes is ever growing, split it up into sections with
comments explaining why each is necessary and what uses it.
Ref: [Test PR](https://github.com/containers/automation/pull/208)
=> Mac PW Pool: Install libkrun (krunkit)

build-push/test/qemusetup.sh
For whatever reason, the `registries.conf` alias setup is no-longer working and the docker rate-limiting is causing CI breakage.  Fix this by simplifying to pulling directly from the google proxy.
=> Fix build-push CI env setup failure

mac_pw_pool/nightly_maintenance.sh
Every night a script runs to check and possibly update all the scripts in the repo.  When this happens, two important activities take place:
1. The script is restarted (presuming it's own code changed).
2. The container running nginx (for the usage graph) is restarted.
For unknown reasons, possibly due to a system update, a pasta (previously slirp4netns) sub-process spawned by podman is holding open the lock-file required by both the maintenance script and the (very important) `Cron.sh`.  This leads to a deadlock situation where the entire pool becomes unmanaged since `Cron.sh` can't run.
To prevent unchecked nefarious/unintended use, all workers automatically recycle themselves after some time should they become unmanaged. Therefore, without `Cron.sh` operating, the entire pool will …
=> Fix deadlock induced MacOS PW Pool collapse

mac_pw_pool/SetupInstances.sh
While processing instances, if the script encounters an instance running past PW_MAX_HOURS, it will force-terminate it.  However, this check was happening before the script had looked up the required 'pub_dns' value. Fix this by relocating the check.
=> Fix 'Expecting pub_dns to be set/non-empty' error

mac_pw_pool/SetupInstances.sh
The agent is required to keep the public key secure since the local and remote user has sudo access.
=> Fail loudly when ssh-agent not running

mac_pw_pool/shutdown.sh
In an attempt to try and prevent terminating an instance while a CI task is running, the shutdown script checks for the existance of an agent process.  Previously a calculation of a timeout for this delay was stored, however it was never actually used.  Fix this by aborting the delay after the timeout has expired.
=> Fix instance shutdown never timing out

mac_pw_pool/SetupInstances.sh, mac_pw_pool/pw_lib.sh
Fixes: #219
For integrity and safety reasons, there are multiple guardrails in place to limit the potential damage of a rogue/broken/misconfigured worker instance may cause. One of these restrictions is a maximum limit on the number of tasks that a worker may execute. However, if the pool is experiencing extraordinary utilization, it's possible that a large number of workers could encounter this limit at/near the same time. Assuming the pool load remains high, this will then further shorten the lifetime of the remaining online instances.
Also:
* Double the limit on allowed tasks (12 was too small based on heavy utilization).
* Double the allowed setup time to account for network slowdowns.
* Show both the soft and hard uptime limits for each worker.
* Issue warning if worker exceeds soft …
=> Fix possible max-tasks PW pool cascade failure

build-push/test/testbuilds.sh, common/test/testlib-platform.sh, renovate/defaults.json5
We have pinned the renovate go version to the lowest version we support
as otherwise it will create PRs that update to new go version which we
always want to take care of manually as it included more changes
usually. While it doesn't prevent renovate from creating these PRs they
always fail as it cannot update to a newer go version so it is clear to
reviewers what is going on.
=> renovate: update to go 1.22

.github/renovate.json5
Previously renovate auto-assigned all updates in this repo to cevich who's no longer on the team.  Fix this, and update the container FQIN comment to a non-docker-hub location (to avoid rate-limit restrictions).
=> Remove renovate cevich auto-assign

renovate/defaults.json5
Chris no longer works on our team and has no time to review them. Add Ed and myself as reviewers for these PR (we already reviewed them anyway) so we get a notification for all PRs and do not miss them.
=> renovate: update image update PR reviewers

ci/Dockerfile, mac_pw_pool/setup.sh
The new macos 15 base image does not contain it and the repo_prep in podman is failing because we need it to compress the tar with it.
=> mac_pw_pool: add zstd

mac_pw_pool/setup.sh
This reverts commit d805c0c822e8a56f288e70184df8726c65df45b2.
Podman should build on 5.5 and main again due
https://github.com/containers/podman/commit/db65baaa215b68d73996ca17dd8c596901ab8bdb
=> Revert "mac_pw_pool: hotfix go install"

renovate/defaults.json5
@Luap99 PTAL, this is required to let Renovate work after updating to Go 1.24, OTOH with https://github.com/containers/podman/pull/26874#issuecomment-3210127533, it might make sense to prefer Renovate working on the main Podman repo for a little while.
=> Update to Go 1.24
